### ISSUE TITLE
Issue to add new Column in existing CSV.

### ISSUE THREAD

**Issue by 2rohith2** [jlawrie/opencsv#2]
CSVReader reader = new CSVReader(new FileReader("fileName.csv"));
List< String[] > myEntries = reader.readAll();

instead of **String[]**, it would be better to have **ArrayList<String>**, so that
myEntries.get(0).add("new_column_content");
String[] is fixed, you can't add data at run-time.

So, that new column can be added easily.
List< ArrayList < String > > myEntries = reader.readAll();

**Comment by tejavenkatlanka** [comment]
No , most of time reading all from csv and adding new column will get improper csv if there length are not equal 
example if column one and two are first name and last name of use if you are adding salary column in 0 index if length is less then it will get first name instead of salary as empty or null
